[package]
name = "rusty-postgres"
version = "0.1.1-beta"
edition = "2021"
authors = ["hariprasath"]
description = "A advanced lightwight ORM and Query Builder for postgres"
license = "MIT"
repository = "https://github.com/HashiramaSenjuhari/zen"
homepage = "https://crates.io/crates/rusty_postgres"
documentation = "https://docs.rs/rusty_oauth/latest/rusty_postgres/"

[dependencies]
# postgres = "0.19.9"
postgres = { version = "0.19.9", features = ["with-uuid-1", "with-chrono-0_4"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.134" }
uuid = { version = "1.11.0" }
chrono = "0.4.39"
rand = "0.8.5"
regex = "1.11.1"

[features]
default = []
full_search = []
ranked_search = []
count = []
pagination = []
similar_search = []
geography = []
brin_index = []
partition = []
horizontal_split = []
