[package]
name = "zen"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.9"
# proc-macro2 = "1.0.89"
# quote = { version = "1.0.37" }
# syn = { version = "2.0.87", features = ["full"] }

# [lib]
# proc-macro = true
