[package]
name = "zen"
version = "0.1.1"
edition = "2021"
authors = ["hariprasath"]
description = "A simple Rust-based postgres server that listens on a postgres server"
license = "MIT"
repository = "https://github.com/HashiramaSenjuhari/zendb"
homepage = "https://crates.io/crates/zendb"
documentation = "https://docs.rs/rusty_oauth/latest/zendb/"

[dependencies]
postgres = "0.19.9"

